Fixed server.js code for balance, balanceHistory, account, accountlevel
Seneca-PlaNA/body-contouring-clinic pull request #146
Opened 2021-02-15 20:26 UTC by sonechca

error fix

2021-02-15 22:36 UTC, eunbeek submitted a review, later dismissed

2021-02-15 23:36 UTC, yuanLeeMidori commented on servers/server.js
> +app.put('/accounts/:id', (req, res) => {
can we make the view/update/delete single object all singular? like `/account/:id` instead of `/accounts/:id`

2021-02-15 23:36 UTC, yuanLeeMidori commented on servers/server.js
>  app.get('/account-level', (req, res) => {
and make *view all* plural, instead of singular

2021-02-15 23:37 UTC, yuanLeeMidori requested changes
please check the api route, make the *view all* plural and make *view/update/delete one* all singular

2021-02-16 01:04 UTC, yuanLeeMidori approved these changes

2021-02-16 02:41 UTC, rko7 approved these changes

2021-02-16 02:41 UTC, rko7 approved these changes

2021-02-16 04:50 UTC, merged