Issue 159 : Passed offerId when Book btn is clicked
Seneca-PlaNA/body-contouring-clinic pull request #172
Opened 2021-02-23 03:56 UTC by eunbeek

2021-02-23 15:00 UTC, yuanLeeMidori requested changes

2021-02-23 15:00 UTC, yuanLeeMidori commented on src/VIP/ListAllOffer.js
> +<<<<<<< HEAD
@eunbeek you might want to fix the conflict

2021-02-24 04:12 UTC, yuanLeeMidori approved these changes

2021-02-24 04:18 UTC, rko7 approved these changes

2021-02-24 05:19 UTC, merged