Issue 188: Main Table and CRUD Handler Creation for FAQ
Seneca-PlaNA/body-contouring-clinic pull request #189
Opened 2021-02-27 05:58 UTC by rko7

2021-02-27 19:52 UTC, yuanLeeMidori commented on models/faq.js
> +    faqCategoryName: {
If we have categories for faqs, I think faqCategory should have its collection, and be linked to faq collection.

2021-02-27 19:54 UTC, yuanLeeMidori requested changes
If we have categories for faqs, I think faqCategory should have its collection, and be linked to faq collection.

2021-02-27 21:42 UTC, rko7 commented
added faqCategory collection

2021-02-28 02:28 UTC, yuanLeeMidori commented
@rko7 I think you changed more in this branch (e.g. the faqCategoryName). I'll wait till you're push more commit, then review.

2021-02-28 04:48 UTC, rko7 commented
changed collection field names

2021-03-01 05:51 UTC, eunbeek approved these changes

2021-03-01 19:56 UTC, yuanLeeMidori approved these changes

2021-03-01 19:56 UTC, merged