Edited customer admin with login
Seneca-PlaNA/body-contouring-clinic pull request #230
Opened 2021-03-10 19:59 UTC by sonechca

2021-03-10 20:41 UTC, eunbeek submitted a review, later dismissed

2021-03-10 20:56 UTC, yuanLeeMidori requested changes

2021-03-10 20:56 UTC, yuanLeeMidori commented on servers/dbConnection.js
> +const mongodbConnectionStr = process.env.MONGODB_URI;
I think you need to comment out `const mongodbConnectionStr = process.env.MONGODB_URI;`, just leave the one with the json file, not sure if you can assign value to one variable twice.

2021-03-10 23:07 UTC, yuanLeeMidori commented on servers/dbConnection.js
> +const mongodbConnectionStr = process.env.MONGODB_URI;
https://github.com/Seneca-PlaNA/body-contouring-clinic/commit/ddf0d2e70c4639ccf27c7a4458f445e201c17c77#diff-ba754de4f166a6110f04e03715725905918bc6202a97e55fd7a7687f4699b7af

The old file before you expose the connection string looks like this, the one with process.env.MONGODB_URI is commented out.

2021-03-10 23:24 UTC, rko7 approved these changes

2021-03-10 23:51 UTC, eunbeek approved these changes

2021-03-11 03:11 UTC, yuanLeeMidori approved these changes

2021-03-11 03:13 UTC, merged